#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '👷 Styling, testing and building your project before committing'

# Check ESLint Standards
pnpm check-lint ||
(
    echo '😤 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false; 
)

# Check tsconfig standards
pnpm check-types ||
(
    echo '🤡 Failed Type check. Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔 Alright. Code looks good to me. Trying to build now.'

pnpm build ||
(
    echo '❌ Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅ You win this time. I am committing this now.'