name: Build and Deploy

on:
  push:
    branches: [develop]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository }}/takeloot-client:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/takeloot-client:latest
          cache-to: type=inline
      
      # - name: Update rancher deployment
      #   uses: th0th/rancher-redeploy-workload@v0.9
      #   env:
      #     RANCHER_BEARER_TOKEN: ${{ secrets.RANCHER_BEARER_TOKEN }}
      #     RANCHER_CLUSTER_ID: 'c-l7qcs'
      #     RANCHER_NAMESPACE: 'default'
      #     RANCHER_PROJECT_ID: 'p-pg7wp'
      #     RANCHER_URL: 'https://rancher.takeloot.ru'
      #     RANCHER_WORKLOADS: 'dev-takeloot-client'